### ISSUE TITLE
Big weird chinese text

### ISSUE THREAD

**Issue by PanekPro** [a2659802/HollowKnight.Decoration#1]
When I load the game, half of the screen is covered in chinese text. I can't interact with that half of the screen. what to do??????

**Comment by a2659802** [comment]
these text is about telling you do not charge for custom level.
just because some chinese selling their skin in public, I managed to prevent this case.
if you want to hidden the text,you can go to SAVES directory and edit "DecorationMaster.GlobalSettings.json".
just SET agreeLicense from false to true. like this: "agreeLicense": true,
then save the settings
if you cant find where the saves directory, you can search in Google or ask in Discord
